# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

title: Social Science Computing Unit Budapest
email: borza.endre@krtk.hu
org_email: BigData@krtk.hu
description: >- # this means to ignore newlines until "baseurl:"
  SSCUB - Social Science Computing Unit Budapest
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: sscu-budapest
github_username:  sscu-budapest

# Build settings
theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
collections:
  - releases
  - topics
  - repos


logo: /assets/krtk-text-en.png
color_scheme: light
aux_links:
  "SSCUB on GitHub":
    - "//github.com/sscu-budapest"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
