title: Social Science Computing Unit Budapest
publisher:
  name: Social Science Computing Unit Budapest
  email: BigData@krtk.hu
author:
  name: Endre Márk Borza
  email: borza.endre@krtk.hu
email: borza.endre@krtk.hu
description: >- # this means to ignore newlines until "baseurl:"
  SSCUB - Social Science Computing Unit Budapest
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sscu-budapest.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: sscu-budapest
github_username:  sscu-budapest

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
collections:
  - releases
  - topics
  - repos


logo: /assets/krtk-text-en.png
color_scheme: light
aux_links:
  "SSCUB on GitHub":
    - "//github.com/sscu-budapest"

