name: Build Site

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Git
      run : |
        git config --global user.name 'Github Actions Build'
        git config --global user.email 'ci@example.org'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build
      run: |
        inv build --commit
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

